t = int(input('entre com um numero inteiro:'))

print('-' *12)
print(f'{t} * 1 = {t*1}')
print(f'{t} * 2 = {t*2}')
print(f'{t} * 3 = {t*3}')
print(f'{t} * 4 = {t*4}')
print(f'{t} * 5 = {t*5}')
print(f'{t} * 6 = {t*6}')
print(f'{t} * 7 = {t*7}')
print(f'{t} * 8 = {t*8}')
print(f'{t} * 9 = {t*9}')
print(f'{t} * 10 = {t*10}')
print('-' *12)